images:
  web:
    reference: public.ecr.aws/docker/library/nginx:1.27.4-alpine
  redis:
    reference: public.ecr.aws/docker/library/redis:7.4.2-alpine
  toolbox:
    reference: public.ecr.aws/docker/library/busybox:1.37.0

web:
  replicas: 1
  servicePort: 80

redis:
  persistence:
    enabled: false
    size: 1Gi
    storageClassName: ""

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    memory: 128Mi
