apiVersion: v1
kind: Service
metadata:
  name: {{ include "target-application.name" . }}-web
  labels:
    {{- include "target-application.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "target-application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.servicePort }}
      targetPort: http

